#! /bin/python

from __future__ import annotations
import os
import sys
import subprocess


def main(argv: str):
    if len(argv) == 1:
        print("Please input a file to run with\n\tlrun <filename> <depth> (optional)")
        return

    current_dir: str = "./"

    needed_file: str  = argv[1]

    max_depth: int = 5

    if len(argv) > 1:
        try:
            max_depth = int(argv[2])
        except:
            print("Depth argument must be an integer")

    is_found: bool = False

    for _ in range(max_depth):
        if needed_file in os.listdir(current_dir):
            subprocess.run([current_dir + needed_file])
            is_found = True
            break

        current_dir += "../"

    print("File was found" if is_found else "File was not found")



if __name__ == "__main__":
    main(sys.argv)
